POST http://localhost:4891/v1/completions HTTP/1.1
Content-Type: application/json
Authorization: Bearer $OPENAI_API_KEY"
# the Bearer <$OPENAI_API_KEY"> is not required,not needed for a local LLM

{
    "model":"mpt-7b-chat",
    "prompt": "Please tell me the things about Golang Programming language.",
    "max_tokens":500,
    "temperature":0.28,
    "top_p":0.95,
   " n":1,
    "echo":true,
    "stream":false
}

GET http://localhost:4891/v1/models HTTP/1.1
Authorization: Bearer $OPENAI_API_KEY"
# the Bearer <$OPENAI_API_KEY"> is not required,not needed for a local LLM

GET http://localhost:4891/v1/models/mpt-7b-chat HTTP/1.1
Authorization: Bearer $OPENAI_API_KEY"
# the Bearer <$OPENAI_API_KEY"> is not required,not needed for a local LLM
